add https environment variables
pulse-admin/api pull request #69
Opened 2017-01-04 20:53 UTC by brianlindsy

2017-01-04 21:13 UTC, kekey1 requested changes

2017-01-04 21:13 UTC, kekey1 commented on pulse/broker/src/main/resources/application.properties.template
> +server.ssl.key-store-password: PuLsE1!$
is this the real password? can we put something fake in the template file?

2017-01-04 21:13 UTC, kekey1 commented on pulse/service/src/main/resources/application.properties.template
> +server.ssl.key-store-password: PuLsE1!$
same - is this a fake password?

2017-01-05 01:34 UTC, andlar approved these changes

2017-01-05 14:38 UTC, kekey1 approved these changes

2017-01-05 14:49 UTC, andlar approved these changes

2017-01-05 14:49 UTC, merged